hyperskill_project:
  id: 83
  ide_files: https://stepik.org/media/attachments/lesson/263287/additional_files.json
  is_template_based: false
stages:
- id: 457
  step: 7486
- id: 458
  step: 7487
- id: 459
  step: 7488
- id: 460
  step: 7489
- id: 461
  step: 7490
- id: 462
  step: 7491
- id: 463
  step: 7492
